apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-apiconnect
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: cp4i-manifests/operators/ibm-apiconnect
    repoURL: https://github.com/sreckoj/argocd-cp4i
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
