apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-group-cert-manager
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: cp4i-manifests/operator-groups/cert-manager-operator-group
    repoURL: https://github.ibm.com/srecko-janjic/argocd-cp4i
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
