---
#
# Event Endpoint Management - Operator version 11.2.0+20240603.010000
#
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-eventendpointmanagement
  namespace: openshift-operators
spec:
  channel: v11.2
  installPlanApproval: Automatic
  name: ibm-eventendpointmanagement
  source: ibm-eventendpointmanagement-catalog
  sourceNamespace: openshift-marketplace
