apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  # annotations:
  #   apiconnect-operator/cp4i: 'true'
  labels:
    backup.apiconnect.ibm.com/component: apiconnectcluster
  name: apic1
  namespace: cp4i
spec:
  analytics:
    mtlsValidateClient: true
  license:
    accept: true
    license: L-DZZQ-MGVN8V
    metric: VIRTUAL_PROCESSOR_CORE
    use: nonproduction
  portal:
    mtlsValidateClient: true
  profile: n1xc7.m48
  version: 10.0.8.0
  storageClassName: ocs-storagecluster-ceph-rbd